name: Prometheus
title: Prometheus监控学习指南
subtitle: '数据库教程 | Designed by YanHuo075'
tags: 监控
icon: https://fastly.jsdelivr.net/gh/yanhuo075/images-repo/upload/prometheus.svg
cover: https://fastly.jsdelivr.net/gh/yanhuo075/images-repo/upload/prometheus.svg
coverpage: true
description: Prometheus 是一套的开源云原生监控系统，以时序数据和 PromQL 为核心，支持动态拉取、告警与可视化。
repo: 
search:
  filter: /wiki/prometheus/
  placeholder: 在Prometheus文档中搜索...
leftbar: 
  - tree
  - timeline_stellar_releases
  - related
base_dir: /wiki/prometheus/
tree:
  '第1章 Prometheus基础知识':
    - introduction
    - arch
  
  '第2章 Prometheus安装和使用':
    - describe
    - install
    - node
    - promsql
    - grafana
    - task

  '第3章 探索PromQL':
    - time-series
    - metric-type
    - promql-learn
    - promql-symbol
    - promql-aggregation
    - promql-function
    - promql-httpapi
    - promql-practices
